### ISSUE TITLE
Filter depending of table and column name

### ISSUE THREAD

**Issue by tomaszkyc** [nene/filter-row#9]
Hi,

I have a question about filtering e.x. column1 in table2. I want to make a sets which will set default filter for table2 and column1 and will disable modifying filter value.

How can I do this ? 

Thanks,

Tomasz

**Comment by nene** [comment]
Hi

It's been years since I developed this component. So you might be better
off looking around in the code by yourself.

Though frankly I don't understand your question. What are those "sets" you
want to make, and which tables and columns are you talking about?

With best,
Rene


11.01.2018 2:33 PM kirjutas kuupäeval "tomaszkyc" <notifications@github.com
>:

Hi,

I have a question about filtering e.x. column1 in table2. I want to make a
sets which will set default filter for table2 and column1 and will disable
modifying filter value.

How can I do this ?

Thanks,

Tomasz

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nene/filter-row/issues/9>, or mute the thread

**Comment by tomaszkyc** [comment]
Hi,

Thank you gór reply. Sets I mean that tableA Has filter X on column1 but after switvhing to tableB will get filterY on column2.


Pozdrawiam / Best regards,
Tomasz Kyc
Microsoft Certified IT Professional | Microsoft Specialist
(+48) 605-880-531 | tomasz.kyc@outlook.com
________________________________

**Comment by nene** [comment]
Well, FilterRow only works with one table. If you want table1 to interact with table2, you'll have to implement such logic by yourself.
